# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24bbf3b156120ac419c6b40c9346517a04832377d88a5219646a232ceaecb6d547ae9062f4dea65d754c216b362f81acd29abc344d756868a6e6bb79becf232e

test:
  secret_key_base: 27341d405f85c7fb83c3f5175a50eee1832bc53b49c9da74451d31b6eae1a1aa8c014e80b4e7841b9bf298b9992dcfc137a62a774ff7155692d9d3e059ba00da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
